### ISSUE TITLE
Not available attribute 'cluster_training'

### ISSUE THREAD

**Issue by sepidehmaghami** [sugarandgugu/GaVaMoE#2]
Hi implementation for `'cluster_training'` not available in the code you published, I got this error: 
```
AttributeError: 'Vae_Cluster_Es' object has no attribute 'cluster_training'
```

**Comment by sugarandgugu** [comment]
hi, please delete “vae_clu.cluster_training(corpus = corpus, cluster_epoch = 100)”， I already updated train.py

**Comment by sepidehmaghami** [comment]
Hello, thank you very much for your help.

After running `inference.py` to generate explainable text, I get the following error. I would appreciate it if you could help me resolve this issue as well.
```
ModuleNotFoundError: No module named 'distinct_n'
```

**Comment by sugarandgugu** [comment]
hi，you can git clone this repo: https://github.com/neural-dialogue-metrics/Distinct-N
, then install.

**Comment by sepidehmaghami** [comment]
Thanks for your help, 

I used maped data from `TorchDataset2HuggingfaceDataset` to `inference.py`, I got this error : 
```
Traceback (most recent call last):
  File "/content/inference.py", line 62, in <module>
    test_cluster_index = save_gate_index(data, vae_clu.cuda())
  File "/content/utils/utils.py", line 158, in save_gate_index
    hf_dataset = hf_dataset.remove_columns(['labels','feature', 'input_ids', 'attention_mask','rating'])
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 602, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2222, in remove_columns
    raise ValueError(
ValueError: Column name ['labels', 'attention_mask', 'rating'] not in the dataset. Current columns in the dataset: ['user', 'item', 'input_ids', 'text', 'feature']
```
Could you help me?

**Comment by sugarandgugu** [comment]
You need to map the dataset to huggingface format first. 
You can see the train_llama3.py.
`   train_dataset = train_dataset.map(
        Prompt_Process(tokenizer, 180),
        batched = False,
    )
    train_dataset.save_to_disk('path')
    `
   Before you run inference.py, please make sure the dataset.

**Comment by sepidehmaghami** [comment]
Thanks for your guidance but I was unable to run it.
I put this in the train.py folder:
`test_dataset.save_to_disk('./dataset/cache/test_dataset_TripAdvisor')`

In inference.py,updated the paths as follows:
```
vae_model_path = './output/TripAdvisor/TripAdvisor_cluster_5_best_weight.pth'
llm_model_path = './output/TripAdvisor_Cluster4/explain'
data_path      = './dataset/cache/test_dataset_TripAdvisor'
excel_path     = './excel/TripAdvisor/llama_TripAdvisor_cluster5.xlsx'
txt_path       = './excel/yelp/llama_TripAdvisor_cluster5.txt'
```
But I still get the following error:
```
Traceback (most recent call last):
  File "/content/inference.py", line 72, in <module>
    vmoe_llama3 = Vmoe_llama3(config = config,tokenizer = tokenizer,gate_index_list = test_cluster_index, user_embed = user_embeds, item_embed = item_embeds, use_lora = False)
  File "/content/model/vamoe.py", line 29, in __init__
    self.change_mlp4moe()
  File "/content/model/vamoe.py", line 58, in change_mlp4moe
    block.mlp = MoeBlock_RS(config = self.config, cluster_index_list = self.gate_index_list, dataset_num = 100).to(torch.bfloat16)
  File "/content/model/moe_layer_llama.py", line 39, in __init__
    self.experts = nn.ModuleList([SparseTop2MLP(config) for _ in range(self.num_experts)])
  File "/content/model/moe_layer_llama.py", line 39, in <listcomp>
    self.experts = nn.ModuleList([SparseTop2MLP(config) for _ in range(self.num_experts)])
  File "/content/model/moe_layer_llama.py", line 15, in __init__
    self.f1 = nn.Linear(self.hidden_dim, self.ffn_dim,    bias = False)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
```

Is it possible to share it if you have the output with TripAdvisor data?
Or explain it in the comments.

**Comment by sugarandgugu** [comment]
I will upload the data later

**Comment by sugarandgugu** [comment]
the size of dataset is more than 25MB，can you give me your email？ I send you directly.

**Comment by sepidehmaghami** [comment]
Yes, of course, thank you very much.
sepideh.d.maghami@gmail.com

**Comment by sugarandgugu** [comment]
done, please check your email.

**Comment by YuChenfu1022** [comment]
> done, please check your email.

I'm also trying to reproduce the code and have encountered the same issue. Could you please share the output with TripAdvisor data with me? It would be a great help for my subsequent code reproduction. Thank you very much!

**Comment by YuChenfu1022** [comment]
> Yes, of course, thank you very much. [sepideh.d.maghami@gmail.com](mailto:sepideh.d.maghami@gmail.com)

Hello, I noticed that you asked if you could get access to the processed TripAdvisor dataset. I am currently experimenting with the code in this paper and was wondering if you would be willing to share a copy of the dataset with me? My email is chenfu-yu@mails.ccnu.edu.cn. 
Thank you very much.
